[project]
name = "llama-router"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docker>=7.1.0",
    "fastapi[standard]>=0.121.1",
    "httpx>=0.28.1",
    "pyyaml>=6.0.3",
]
